import { db } from '@/db';
import { users, userStats } from '@/db/schema';
import { eq } from 'drizzle-orm';
import bcrypt from 'bcrypt';

async function main() {
    const password = 'kemoda2025';
    const hashedPassword = await bcrypt.hash(password, 10);
    const currentTimestamp = new Date().toISOString();

    const adminAccounts = [
        {
            displayId: 'ADMN#0001',
            email: 'topwriteessays@gmail.com',
            password: hashedPassword,
            name: 'Admin User 1',
            role: 'admin',
            approved: true,
            balance: 0,
            earned: 0,
            totalEarnings: 0,
            rating: null,
            phone: '+254700000001',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            profilePictureUrl: null,
            lastLoginAt: null,
            lastLoginIp: null,
            lastLoginDevice: null,
            loginCount: 0,
            domainId: null,
            freelancerBadge: null,
            clientTier: 'basic',
            clientPriority: 'regular',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0002',
            email: 'm.d.techpoint25@gmail.com',
            password: hashedPassword,
            name: 'Admin User 2',
            role: 'admin',
            approved: true,
            balance: 0,
            earned: 0,
            totalEarnings: 0,
            rating: null,
            phone: '+254700000002',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            profilePictureUrl: null,
            lastLoginAt: null,
            lastLoginIp: null,
            lastLoginDevice: null,
            loginCount: 0,
            domainId: null,
            freelancerBadge: null,
            clientTier: 'basic',
            clientPriority: 'regular',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0003',
            email: 'maguna956@gmail.com',
            password: hashedPassword,
            name: 'Admin User 3',
            role: 'admin',
            approved: true,
            balance: 0,
            earned: 0,
            totalEarnings: 0,
            rating: null,
            phone: '+254700000003',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            profilePictureUrl: null,
            lastLoginAt: null,
            lastLoginIp: null,
            lastLoginDevice: null,
            loginCount: 0,
            domainId: null,
            freelancerBadge: null,
            clientTier: 'basic',
            clientPriority: 'regular',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0004',
            email: 'tasklynk01@gmail.com',
            password: hashedPassword,
            name: 'Admin User 4',
            role: 'admin',
            approved: true,
            balance: 0,
            earned: 0,
            totalEarnings: 0,
            rating: null,
            phone: '+254700000004',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            profilePictureUrl: null,
            lastLoginAt: null,
            lastLoginIp: null,
            lastLoginDevice: null,
            loginCount: 0,
            domainId: null,
            freelancerBadge: null,
            clientTier: 'basic',
            clientPriority: 'regular',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0005',
            email: 'maxwellotieno11@gmail.com',
            password: hashedPassword,
            name: 'Admin User 5',
            role: 'admin',
            approved: true,
            balance: 0,
            earned: 0,
            totalEarnings: 0,
            rating: null,
            phone: '+254700000005',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            profilePictureUrl: null,
            lastLoginAt: null,
            lastLoginIp: null,
            lastLoginDevice: null,
            loginCount: 0,
            domainId: null,
            freelancerBadge: null,
            clientTier: 'basic',
            clientPriority: 'regular',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0006',
            email: 'ashleydothy3162@gmail.com',
            password: hashedPassword,
            name: 'Admin User 6',
            role: 'admin',
            approved: true,
            balance: 0,
            earned: 0,
            totalEarnings: 0,
            rating: null,
            phone: '+254700000006',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            profilePictureUrl: null,
            lastLoginAt: null,
            lastLoginIp: null,
            lastLoginDevice: null,
            loginCount: 0,
            domainId: null,
            freelancerBadge: null,
            clientTier: 'basic',
            clientPriority: 'regular',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    for (const admin of adminAccounts) {
        try {
            const existingUser = await db.select().from(users).where(eq(users.email, admin.email)).limit(1);

            if (existingUser.length > 0) {
                console.log(`⚠️ User with email ${admin.email} already exists. Skipping...`);
                continue;
            }

            const insertedUsers = await db.insert(users).values(admin).returning();
            const insertedUser = insertedUsers[0];

            await db.insert(userStats).values({
                userId: insertedUser.id,
                totalJobsPosted: 0,
                totalJobsCompleted: 0,
                totalJobsCancelled: 0,
                totalAmountEarned: 0,
                totalAmountSpent: 0,
                averageRating: null,
                totalRatings: 0,
                onTimeDelivery: 0,
                lateDelivery: 0,
                revisionsRequested: 0,
                createdAt: currentTimestamp,
                updatedAt: currentTimestamp,
            });

            console.log(`✅ Successfully created admin: ${admin.email} with stats`);
        } catch (error) {
            console.error(`❌ Failed to create admin ${admin.email}:`, error);
        }
    }

    console.log('✅ Admin accounts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});