import { db } from '@/db';
import { users } from '@/db/schema';
import bcrypt from 'bcrypt';

async function main() {
    const hashedPassword = await bcrypt.hash('kemoda2025', 10);
    const currentTimestamp = new Date().toISOString();

    const adminUsers = [
        {
            email: 'topwriteessays@gmail.com',
            password: hashedPassword,
            name: 'Admin User 1',
            phone: '+254700000001',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            email: 'm.d.techpoint25@gmail.com',
            password: hashedPassword,
            name: 'Admin User 2',
            phone: '+254700000002',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            email: 'maguna956@gmail.com',
            password: hashedPassword,
            name: 'Admin User 3',
            phone: '+254700000003',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            email: 'tasklynk01@gmail.com',
            password: hashedPassword,
            name: 'Admin User 4',
            phone: '+254700000004',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            email: 'maxwellotieno11@gmail.com',
            password: hashedPassword,
            name: 'Admin User 5',
            phone: '+254700000005',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            email: 'ashleydothy3162@gmail.com',
            password: hashedPassword,
            name: 'Admin User 6',
            phone: '+254700000006',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(users).values(adminUsers);

    console.log('✅ Admin users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});