import { db } from "@/db";
import { users } from "@/db/schema";
import * as bcrypt from 'bcryptjs';

async function main() {
    const password = await bcrypt.hash('kemoda2025', 10);
    const currentTimestamp = new Date().toISOString();

    const sampleUsers = [
        {
            displayId: 'ADMN#0001',
            email: 'topwriteessays@gmail.com',
            password: password,
            name: 'Admin User 1',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            phone: '+254700000001',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0002',
            email: 'm.d.techpoint25@gmail.com',
            password: password,
            name: 'Admin User 2',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            phone: '+254700000002',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0003',
            email: 'maguna956@gmail.com',
            password: password,
            name: 'Admin User 3',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            phone: '+254700000003',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0004',
            email: 'tasklynk01@gmail.com',
            password: password,
            name: 'Admin User 4',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            phone: '+254700000004',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0005',
            email: 'maxwellotieno11@gmail.com',
            password: password,
            name: 'Admin User 5',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            phone: '+254700000005',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            displayId: 'ADMN#0006',
            email: 'ashleydothy3162@gmail.com',
            password: password,
            name: 'Admin User 6',
            role: 'admin',
            approved: true,
            balance: 0,
            rating: null,
            phone: '+254700000006',
            status: 'active',
            suspendedUntil: null,
            suspensionReason: null,
            blacklistReason: null,
            rejectedAt: null,
            rejectionReason: null,
            totalEarned: 0,
            totalSpent: 0,
            completedJobs: 0,
            completionRate: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        }
    ];

    const insertedUsers = await db.insert(users).values(sampleUsers).returning();

    const sampleUserStats = insertedUsers.map((user) => ({
        userId: user.id,
        totalJobsPosted: 0,
        totalJobsCompleted: 0,
        totalJobsCancelled: 0,
        totalAmountEarned: 0,
        totalAmountSpent: 0,
        averageRating: null,
        totalRatings: 0,
        onTimeDelivery: 0,
        lateDelivery: 0,
        revisionsRequested: 0,
        createdAt: currentTimestamp,
        updatedAt: currentTimestamp,
    }));

    await db.insert(userStats).values(sampleUserStats);

    console.log('✅ Admin users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});